file(READ "${INPUT}" input_text)
foreach(n RANGE 4 8)
  string(REPLACE "n_mechanisms=8" "n_mechanisms=${n}" case_text "${input_text}")
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/test_anelastic_cQ_n${n}.in")
  file(WRITE "${case_input}" "${case_text}")
  execute_process(COMMAND "${MPIEXEC}" -np 1 "${EXE}" "${case_input}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "anelastic-cQ N=${n} failed: ${error}\n${output}")
  endif()
  string(FIND "${output}" "anelastic-cQ mechanisms: ${n}" count_position)
  string(REGEX MATCH "cQ final state: max\\|field\\|=[^\n]+" state "${output}")
  if(count_position EQUAL -1 OR state STREQUAL "")
    message(FATAL_ERROR "anelastic-cQ N=${n} diagnostics are missing")
  endif()
  if(state MATCHES "max\\|memory\\|= *0\\.0+E\\+00")
    message(FATAL_ERROR "anelastic-cQ N=${n} did not evolve memory variables")
  endif()
endforeach()
