file(READ "${INPUT}" input_text)
set(cases n3 n9 fixed4)
foreach(case_name IN LISTS cases)
  set(case_text "${input_text}")
  if(case_name STREQUAL "n3")
    string(REPLACE "n_mechanisms=8" "n_mechanisms=3" case_text "${case_text}")
  elseif(case_name STREQUAL "n9")
    string(REPLACE "n_mechanisms=8" "n_mechanisms=9" case_text "${case_text}")
  else()
    string(REPLACE "n_mechanisms=8" "n_mechanisms=4" case_text "${case_text}")
    string(REPLACE "coefficient_policy='nnls-block-ps'" "coefficient_policy='fixed-q50'" case_text "${case_text}")
  endif()
  set(case_input "${CMAKE_CURRENT_BINARY_DIR}/test_anelastic_cQ_invalid_${case_name}.in")
  file(WRITE "${case_input}" "${case_text}")
  execute_process(COMMAND "${MPIEXEC}" -np 1 "${EXE}" "${case_input}"
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  string(FIND "${output}${error}" "CFG-CQ-001" diagnostic_position)
  if(diagnostic_position EQUAL -1)
    message(FATAL_ERROR "anelastic-cQ invalid case ${case_name} did not report CFG-CQ-001")
  endif()
endforeach()
